### ISSUE TITLE
Applying Filters to RecipeBooks fails

### ISSUE THREAD

**Issue by Supermac30** [CSC207-UofT/course-project-group-039-foodies#89]
I'm not sure why this is happening, but I suspect that it has something to do with the fact that RecipeCollection only filters when its iterator is used.

**Comment by dohyunkim02** [comment]
I think that is true. Sorting and filtering recipes happen inside the iterator() so it sorts or filters when the iterator() is called.

**Comment by Supermac30** [comment]
This is fixed in pull request #95
